### ISSUE TITLE
all binding breaking

### ISSUE THREAD

**Issue by lampie22** [BlueFinBima/DCS-AV-8B-NA-Profile#13] opened 2021-11-13 14:11 UTC
hi. 

when i load the profile i get the following in the console. it then deleates all the bindings from the profile.
i have tried fresh helios installs, fresh profiles and starting and binding my own profile from scratch , rolling back helios with the same results. 

thanks
[log.txt](https://github.com/BlueFinBima/DCS-AV-8B-NA-Profile/files/7532447/log.txt)
_Edited to move diagnostics to an attachment to aid readability._

**Comment by BlueFinBima** [comment] 2021-11-13 17:18
@lampie22 Thanks for raising this.  This issue is a duplicate of #12  which was closed as the profile working as designed, because it is actually a regression in Helios 1.6.5xxx.x https://github.com/HeliosVirtualCockpit/Helios/issues/486.  Luckily there is a Helios hotfix, 1.6.5101.0 just about to be released to fix the problem.  I suggest that you monitor https://github.com/HeliosVirtualCockpit/Helios/releases for the release which hopefully will be in a matter of hours away.
You might also be interested in #14 .  While this has not been fixed in a released version of Helios, the referenced issue contains a temporary fix.

**Comment by BlueFinBima** [comment] 2021-11-14 07:53
https://github.com/HeliosVirtualCockpit/Helios/releases/tag/1.6.5101.0 is now available.

**Closed as completed by BlueFinBima** 2021-11-14 07:53 UTC
Labels: duplicate
